### ISSUE TITLE
Question: Bulk nanopore RNA-seq?

### ISSUE THREAD

**Issue by alexandruioanvoda** [jon-xu/scSplit#18]
Hi! Really cool method!

I was wondering whether your package would support bulk RNA-seq? And nanopore-based (i.e. not Illumina short) reads? Is support for other genomes (e.g. other mammalians) easily configurable?

**Comment by jon-xu** [comment]
Thanks for the interest!
Unfortunately this tool is designed for single cell RNA-seq, and thus cannot support bulk data.
As to nanopore, if it is single cell, once you have mapped the long reads and called variants using nanopore tools, the rest should be the same, but we haven't tested it.
The support for other genomes is easy because we only need the BAM file and don't care which genome it used for mapping.
