### ISSUE TITLE
Issue with scSplit count function...

### ISSUE THREAD

**Issue by SathiyaNManivannan** [jon-xu/scSplit#19]
Hello!

I am trying to use scSplit on single-cell data with pooled samples from mouse embryos. The data was processed using 10x Cell Ranger. The output bam file was processed per instructions on the GitHub page and the vcf file was generated using freebayes. I then used bcftools to filter the vcf files based on quality.

When I try to use scSplit on the vcf file, I keep running into an error!

``Traceback (most recent call last): 
    File "scSplit/scSplit", line 699, in <module>
         scSplit()
    File "scSplit/scSplit, line 357, in __init__
        getattr(self, args.command) ()
    File "scSplit/scSplit", line 460, in count
        raise ValueError('Empty matrices!')
ValueError: Empty matrices!
``
Python --version
Python 3.8.2

Please help with troubleshooting this issue!

Thanks,

Sincerely,

Sathiya

`

**Comment by jon-xu** [comment]
Sathiya,

According to the guideline:
g) If this step fails, please check: 1) is your barcode tag in the BAM files "CB" - if not, you need to specify it using -t/--tag; 2) are you working on a mixed sample VCF rather than a simple merge of individual genotypes? 3) is the correct whitelist barcode file being used? The whitelist should be the trusted barcodes from your sequencing result, not the whole barcode library of the sequencing protocol.

BTW, our tool was tested for 8 or less mixed samples only.
And also it is recommended you remove the doublets using other doublet finding tools before running scSplit to improve the accuracy.
