### ISSUE TITLE
Running time

### ISSUE THREAD

**Issue by IBDgenomics** [jon-xu/scSplit#26]
Hi, 

Running _scSplit count_ is taking forever. I assume is because the number of variants from freebayes is pretty high (>1.3M). I'm running a pool of 4 samples, ~11k cells. 

`Num Pos: 312637, Num barcodes: 11037`

Do you have any recommendation on how to handle this? Filtering somehow the freebayes vcf to reduce the number of variants? Would it make sense to run scSplit count by region/chromosome and build a consensus after that?

Thanks in advance

**Comment by jon-xu** [comment]
﻿Hi,

1.3 Million looks a bit too many for me. And this should be the reason of long running time.

Cheers,

Jon

On 10 Nov 2023, at 19:47, IBDgenomics ***@***.***> wrote:

﻿

Hi,

Running scSplit count is taking forever. I assume is because the number of variants from freebayes is pretty high (>1.3M). I'm running a pool of 4 samples, ~11k cells.

Do you have any recommendation on how to handle this? Filtering somehow the freebayes vcf to reduce the number of variants? Would it make sense to run scSplit count by region/chromosome and build a consensus after that?

Thanks in advance
