### ISSUE TITLE
pandas "append" function for DataFrame object is deprecated

### ISSUE THREAD

**Issue by G3N0M3** [jon-xu/scSplit#27]
While running scSplit run, I came to an error that there is no "append" function for DataFrame objects.

I found out that the append function is deprecated since version 1.4.0, and substituted with "concat".

I was able to get results with some warnings and using pandas version 2.1.3,
with some modifications in line 588 and 593.

```
assignments = pd.DataFrame()
for n in range(num):
    assignment = pd.DataFrame()
    assignment['Barcode'] = model.reassigned[n]
    if n != model.doublet:
        assignment['Cluster'] = 'SNG-' + str(n)
        assignments = pd.concat([assignments, assignment])
        if doublets != 0:   # if doublet cluster is expected
            assignment = pd.DataFrame()
            assignment['Barcode'] = model.reassigned[model.doublet]
            assignment['Cluster'] = 'DBL-' + str(model.doublet)
            assignments = pd.concat([assignments, assignment])
            assignments.to_csv(os.path.join(args.out, r'scSplit_result.csv'), sep='\t', index=False)
            model.P_s_c.to_csv(os.path.join(args.out, r'scSplit_P_s_c.csv'))
            with open(os.path.join(args.out, r'scSplit_dist_variants.txt'), 'w') as logfile:
                for item in model.dist_variants:
                    logfile.write(str(item) + '\n')
                    model.dist_matrix.to_csv(os.path.join(args.out, r'scSplit_dist_matrix.csv'), float_format='%.0f')
                    model.pa_matrix.to_csv(os.path.join(args.out, r'scSplit_PA_matrix.csv'), float_format='%.0f')
```

Can your side confirm that the modification is valid and will produce the intended results?
Thanks!

**Comment by jon-xu** [comment]
﻿Hi Eunjun,

We developed on earlier version of pandas.

Thanks for letting us know the depreciation of append function.

Based on pandas documentation, I think your amendment is consistent with previous append function.

Unfortunately we don’t have plan to catch up all updates in different packages. Thus we couldn’t test your amendments. Sorry about that!

Good luck!

Jon

On 3 Dec 2023, at 22:23, Eunjun Choi ***@***.***> wrote:

﻿

While running scSplit run, I came to an error that there is no "append" function for DataFrame objects.

I found out that the append function is deprecated since version 1.4.0, and substituted with "concat".

I was able to get results with some warnings and using pandas version 2.1.3

assignments = pd.DataFrame()
for n in range(num):
    assignment = pd.DataFrame()
    assignment['Barcode'] = model.reassigned[n]
    if n != model.doublet:
        assignment['Cluster'] = 'SNG-' + str(n)
        assignments = pd.concat([assignments, assignment])
        if doublets != 0:   # if doublet cluster is expected
            assignment = pd.DataFrame()
            assignment['Barcode'] = model.reassigned[model.doublet]
            assignment['Cluster'] = 'DBL-' + str(model.doublet)
            assignments = pd.concat([assignments, assignment])
            assignments.to_csv(os.path.join(args.out, r'scSplit_result.csv'),     sep='\t', index=False)
            model.P_s_c.to_csv(os.path.join(args.out, r'scSplit_P_s_c.csv'))
            with open(os.path.join(args.out, r'scSplit_dist_variants.txt'), '    w') as logfile:
                for item in model.dist_variants:
                    logfile.write(str(item) + '\n')
                    model.dist_matrix.to_csv(os.path.join(args.out, r'scSplit_dist_ma    trix.csv'), float_format='%.0f')
                    model.pa_matrix.to_csv(os.path.join(args.out, r'scSplit_PA_matrix    .csv'), float_format='%.0f')


Can your side confirm that the modification is valid and will produce the intended results?
Thanks!

**Comment by G3N0M3** [comment]
@jon-xu Thanks!
