### ISSUE TITLE
output to different directory

### ISSUE THREAD

**Issue by drneavin** [jon-xu/scSplit#9]
Hi Jon,

I am wondering if there is a method to indicate a directory where you want the output of `scSplit run` and `scSplit genotype`? It would be great if I don't have to cd to the directory where I want them to be before running it.

Thanks!

-Drew

**Comment by jon-xu** [comment]
Hi Drew,

Yes I have added it in the newest release v1.0.5.
Please re-download and try.

Thanks for pointing it out!

Jon

**Comment by drneavin** [comment]
Fantastic! Thanks Jon!

**Comment by drneavin** [comment]
Thanks for putting in this functionality Jon! I just tested it out with the new release and it looks like it works nicely for `scSplit run` and `scSplit genotype` but you still need to put the full path for the `scSplit count` options `-r` and `-a`. Would you be able to make it so that it automatically puts the alt and ref matrices in the designtated out directory?

**Comment by jon-xu** [comment]
Ok, I thought you could add path in -r/-a parameters, but you’re right, better to make it consistent.

Will revise and let you know.

Cheers,

Jon

On 1 Apr 2020, at 14:47, drneavin <notifications@github.com> wrote:

﻿

Thanks for putting in this functionality Jon! I just tested it out with the new release and it looks like it works nicely for scSplit run and scSplit genotype but you still need to put the full path for the scSplit count options -r and -a. Would you be able to make it so that it automatically puts the alt and ref matrices in the designtated out directory?

**Comment by jon-xu** [comment]
It's now built in v1.0.6.

Thanks again!

**Comment by jon-xu** [comment]
Please use the newest v1.0.7 instead (bug fixes).
